name: Project Cards Automation

on:
  workflow_dispatch:

jobs:
  add-cards:
    runs-on: ubuntu-latest

    steps:
      - name: Criar cards no GitHub Projects
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const cards = [
              "Finalizar configuração de domínio no Registro.br",
              "Apontar DNS para Vercel (ns1/ns2.vercel-dns.com)",
              "Verificar propagação total do domínio",
              "Ajustar favicon e título do painel ERP",
              "Atualizar título da aba e ícone no layout",
              "Concluir estilização da mandala de módulos",
              "Aplicar cores e ícones definitivos",
              "Adicionar efeitos (hover, som, animação leve)",
              "Criar cards visuais dos módulos ERP na tela principal",
              "Vendas, Compras, PCP, Expedição, Fiscal, Financeiro etc",
              "Criar tela de login com autenticação JWT",
              "Backend Django + DRF",
              "Frontend com validação e roteamento"
            ];

            const owner = "Wigorb";
            const projectNumber = 1;

            const { data: projects } = await github.rest.projects.listForUser({ username: owner });
            const project = projects.find(p => p.number === projectNumber);
            const columns = await github.rest.projects.listColumns({ project_id: project.id });
            const backlog = columns.data.find(c => c.name.toLowerCase().includes("pendência") || c.name.toLowerCase().includes("backlog"));

            for (const card of cards) {
              await github.rest.projects.createCard({
                column_id: backlog.id,
                note: `📌 ${card}`
              });
            }
